version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    depends_on:
      - frontend

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
